# Build Command:
# docker build -t bcollazo/catanatron-server:latest .. -f catanatron/Dockerfile.web
FROM python:3.12

WORKDIR /app

RUN pip install --upgrade pip

COPY . .
RUN pip install -e ./catanatron[web]
RUN pip install -e .
RUN pip install torch --index-url https://download.pytorch.org/whl/cpu

EXPOSE 5001

ENV FLASK_DEBUG=1
ENV FLASK_APP=catanatron.web
ENV FLASK_RUN_HOST=0.0.0.0
ENV FLASK_RUN_PORT=5001

CMD flask run
